# Code review {{< iconify fa6-solid pencil >}} {#sec-review}

As code review is a big topic, we will only discuss here what we strive for, what we'd like our community to do, and point people to relavant information. We're always open to feedback (see *Edit this page* to the right)!

## Scope

The scope of this guide is for work within the WILDS GitHub organization (<https://github.com/getwilds/>). In  chapters within **Code review** we have the following sections:

Contributions to the WILDS:

- from within team DASL (@sec-review-dasl)
- from non-DASL folks, and (@sec-review-external)

And

- advice for broader Fred Hutch community (@sec-review-general)

## Infrastructure

We use a number of helpful tools to facilitate code changes, including code review:

- Contributing instructions in the file `CONTRIBUTING.md`
- Pull request instructions in a file `pull_request_template.md`
- Issue instructions in a file `issue_template.md`

Read more about these files in the section @sec-conventions-repos.

