# Welcome {.unnumbered}

::: {.callout-warning}
This guide is under construction - content changes often.
:::

This book is a resource for the community of people using, contributing to, and maintaining software within the WILDS GitHub organization (<https://github.com/getwilds>) at the Fred Hutch Cancer Center Data Science Lab ([DaSL][]).

The book covers important aspects of software development, including how to get involved in software as a user or contributor, code style, code review, package documentation, and more. It includes both internal facing guidelines as well as for any contributions from folks other than DaSL staff.

In the WILDS we primarily develop software in the [R][] and [Python][] programming languages. Where necessary, we'll discuss a topic with respect to both languages.

## Inspiration

Inspiration for this guide is taken in part from:

- [Tidyverse Style Guide](https://style.tidyverse.org/)
- [rOpenSci Dev Guide](https://devguide.ropensci.org/)

## License

This book is licensed to you under [Creative Commons CC0 1.0 Universal (CC0 1.0)][cc0], i.e. public domain.

## Rules

Throughout this book we highlight rules that we strive to enforce for projects where deemed necessary. These rules are made more clear and easy to find by using a badge with an icon like:

{{< var rule-badge >}} {{< var rule-eg >}}

Why do certain things constitute a rule while others do not? We offer the following guard rails in lieu of a clear answer:

- rules are likely to be concrete enough to easily allow human or ideally machine checks
- rules are likley to be the issues we feel are most important

[DaSL]: https://hutchdatascience.org/
[R]: https://www.r-project.org/
[Python]: https://www.python.org/
[cc0]: https://creativecommons.org/publicdomain/zero/1.0/
